name: Upgrade dependencies

on:
  schedule:
    # https://crontab.guru/#0_8_*_*_6
    # At 08:00 on Saturday
    - cron: '0 8 * * 6'
  workflow_dispatch:

concurrency:
  group: upgrade-dependencies
  cancel-in-progress: true

jobs:
  upgrade-dependencies:
    uses: nhoizey/upgrade-dependencies/.github/workflows/upgrade-dependencies.yml@main
    secrets: inherit
